CREATE ROLE dev;
ALTER ROLE dev WITH LOGIN PASSWORD 'password-dev' NOSUPERUSER NOCREATEDB NOCREATEROLE;
GRANT dev TO postgres;
CREATE DATABASE ptodo_dev OWNER dev;
REVOKE ALL ON DATABASE ptodo_dev FROM PUBLIC;
GRANT CONNECT ON DATABASE ptodo_dev TO dev;
GRANT ALL ON DATABASE ptodo_dev TO dev;

CREATE ROLE test;
ALTER ROLE test WITH LOGIN PASSWORD 'password-test' NOSUPERUSER NOCREATEDB NOCREATEROLE;
GRANT test TO postgres;
CREATE DATABASE ptodo_test OWNER test;
REVOKE ALL ON DATABASE ptodo_test FROM PUBLIC;
GRANT CONNECT ON DATABASE ptodo_test TO test;
GRANT ALL ON DATABASE ptodo_test TO test;
